### ISSUE TITLE
Automatically generate data folder structure

### ISSUE THREAD

**Issue by hawkrobe** [hawkrobe/reference_games#14]
Currently, new experiments expect data folders to already exist, e.g.

```
Error: ENOENT: no such file or directory, open '../data/3dObjects/chatbox_basic//message/2017-61-5-22-5-59-416_3812-f5d25c54-b43c-4557-a877-505d46db34a0.csv'
```

Also, should add an option to only write out data in 'production mode' (can get quite cluttered)

**Comment by andrewjong** [comment]
Is there an option now that only writes data during production mode?

**Comment by hawkrobe** [comment]
I haven't made a nice command line argument yet but yes! In game.core.js, at the top of defining all the config properties you can set 

this.dataStore = []

while testing and then when you're ready to test data output or run for production, switch to

this.dataStore = ['csv']

or ['mongo'] to write to a mongo database, or include both in the list to write to both places!
